<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Index.aspx.cs" Inherits="H1WebPage.Index" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Index page</title>
</head>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css"/>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link rel="stylesheet" href="IndexStyle.css"
<body>
    <form id="form1" runat="server">
        <div>
            <header>
                <div class="jumbotron">
                    <h3>MOVIES</h3>
                    
                </div>
                <div class="movies">
                    <asp:GridView ID="grid" runat="server" AutoGenerateColumns="false" OnRowDeleting="grid_RowDeleting" AutoGenerateDeleteButton="true">
                        <Columns>
                            <asp:BoundField DataField="Title" HeaderText="Title"/>
                            <asp:BoundField DataField="Description" HeaderText="Description"/>
                            <asp:BoundField DataField="Year" HeaderText="Year"/>
                            <asp:BoundField DataField="Genre" HeaderText="Genre"/>
                        </Columns>
                    </asp:GridView>
                </div>
                <div class="inputs">
                    <input runat="server" type="text" id="titleInput" placeholder="Movie Title"/>
                    <input runat="server" type="text" id="descInput" placeholder="Movie Description"/>
                    <input runat="server" type="number" id="yearInput" placeholder="Movie Year"/>
                    <input runat="server" type="text" id="genreInput" placeholder="Movie Genre"/>
                    <asp:Button runat="server" ID="addBtn" type="button" Text="Add Movie" class="btn btn-info btn-md" OnClick="Unnamed_Click"/>
                </div>
            </header>
        </div>
    </form>
</body>
</html>
